apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: base-apparel-coming-soon-app
    newName: base-apparel-coming-soon-app
    newTag: latest
